version: '3.7'
services:
    postgres:
        image: postgres:14
        restart: always
        environment:
          - POSTGRES_USER=pent
          - POSTGRES_PASSWORD=pent
          - POSTGRES_DB=pent
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080